version: '3.8'
services:
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes: 
      - db:/var/lib/postgresql/data
  api:
    image: 
    restart: always
    environment:
      - PostGres_Connectionstring= 'Host=db; Database=dotnet-6-crud-api; Username=postgres; Password=postgres;'
    ports:
      - '50000:80'
      - '50000:443'
volumes:
  db:
    driver: local