version: '3.8'
services:
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes: 
      - db:/var/lib/postgresql/data
    expose:
      - '5432'
  api:
    image: rothexd/funawesomegame
    restart: always
    environment: 
      - PostGres_Connectionstring="Host=db; Database=dotnet-6-crud-api; Username=postgres; Password=postgres;"
    ports:
      - '80:80'
    links:
      - db
volumes:
  db:
    driver: local